### ISSUE TITLE
demo.exe  issue

### ISSUE THREAD

**Issue by greenozon** [fjqisba/VmpHelper#5]
there is an issue on your demo.exe sample on the latest build (built in VS)
it produces asset when trying to execute VMP handler   (ACTION_VMP350)

![image](https://github.com/fjqisba/VmpHelper/assets/765343/21f11c98-cdf6-4899-8f7f-394eba939c86)

```
Exception thrown at 0x000007FEFCBFBE0D in ida.exe: Microsoft C++ exception: ghidra::LowlevelError at memory location 0x0000000000603A10.
Debug Assertion Failed!

Program: c:\Prg\Hi\DAPro83\plugins\Revampire.dll
File: C:\Dev\VS2019\VC\Tools\MSVC\14.29.30133\include\vector
Line: 1553

Expression: vector subscript out of range

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)
ida.exe has triggered a breakpoint.
```

**Comment by fjqisba** [comment]
fixed

**Comment by greenozon** [comment]
I tried latest master branch sources but it still crashes...

![image](https://github.com/fjqisba/VmpHelper/assets/765343/a26c317d-4ffb-4aa8-a83f-7a164c82151a)


![image](https://github.com/fjqisba/VmpHelper/assets/765343/aa40fedd-06c6-487c-8b83-b46a4a77748e)

**Comment by greenozon** [comment]
does your demo exe work in your case?

**Comment by fjqisba** [comment]
sorry,I haven't tested it, and it may be due to compilation cache, but I can pass it here.
you can try commenting out the tryGetVmCallExitAddress function，In fact, this function is of little use at the moment.
The development of this project is still in the research stage, and there are still many options that need to be explored.So I don't care about fixing these small bugs now.

**Comment by greenozon** [comment]
Thank you for fast reply
the compilation cache is really huge (1.5 GB)
I'll comment out `tryGetVmCallExitAddress`  as you suggested

PS I"m using VS2019 + Ida83 (32bit debug mode build)
